language: java
jdk:
  - openjdk11
after_success:
  - bash <(curl -s https://codecov.io/bash)

addons:
  sonarcloud:
    organization: "uhlme"
    token:
      secure: "CsFlEYuNZQVgTt8xNHe3RVkJUxnd1D18flSWEensX7wSJlQ43DA1zmRcC6cNUAo5Uvc9OEJM5Z0PTmU/jyznqT2CTuyHvL1uvUv4tKkqVNfA76jCPA7pZ85AzApNE5+NxZaB1u+DDWq4ZFT7gKyFW3ROy9zD8pTvpoa046iAJxJVaxE794MyKxyFiAXkU29WtO5+52sjMpPDR/pdrlrEXXe6q3ze0Iui2e0Ly1DJodCQQNGYN96zRaEXuvQ/vEmeFpgRHG16Z50wgQFBR+zkQfq+VhSoKDFTBstDIGGgAatzozagyslObEGQaR+zf8bqeO3E5l+N+4ZebMGzoDJqrO5laDDtVP/YLuTwzeS4TB8P0UfDNTztV06FOwtAflWBpfZonotpddC9yYx1+zlVvOSMR0YVMzXMMnm1zqi0tSjoNmEhjVSX8xpQQgNgLLjGvDlTZqQa6u+Se2bIxXF+RYtNdP688FDgMI3x5OoY92vvB2Y93EItYUhMW1/7p9yejxb3Gu/fnqiCRTDnAQLVFQElrrKaujtnH1CFVjEMzBIyZoGQi6ljPzmvHj3p4+bz2unxF+dre2/OBJA3BaHFt5H1zuqe9esKEAvnYw/RZo31SHEd/DwikOhJhhKkp8aZutgQBVaIDKujfFwOuSvLIDM0+owfsiEmIs8xNUnHuYQ="

script:
  - ./gradlew check sonarqube
